name: Release dump Binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Create build directory
        run: mkdir -p build

      - name: Build and package release
        run: make release
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
          VERSION: ${{ steps.version.outputs.version }}

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dump-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
