name: Release dump Binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Get version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build Linux Binary
        run: |
          BINARY_NAME="dump"
          go build -ldflags="-s -w -X main.version=${{ steps.version.outputs.version }}" -o $BINARY_NAME .
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0

      - name: Create tarball
        run: |
          mkdir -p dump-linux-amd64/bin
          cp dump dump-linux-amd64/bin/
          tar czf dump-linux-amd64.tar.gz dump-linux-amd64

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dump-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
